version: '3'

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports: 
            - 8080:8080
        volumes:
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /home/jan/django-projects/mychat/static/:/home/jan/django-projects/mychat/static/

    redis:
        image: redis:latest
        ports:
            - 6379:6379
    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: DB_USER
            POSTGRES_PASSWORD: DB_PASSWORD
            POSTGRES_DB: DB_TEST
        hostname: localhost
        ports:
            - 5432:5432 

    webapp:
        build: .
        ports:
            - 8000:8000
    

